version: '3'

services:
    mysql:
        image: mysql:latest
        container_name: pflamenca_mysql
        restart: unless-stopped
        tty: true
        ports:
            - 3326:3306
        environment:
            MYSQL_DATABASE: pflamenca
            MYSQL_ROOT_PASSWORD: pflamenca
            MYSQL_USER: pflamenca
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./.docker/mysql:/var/lib/mysql

volumes:
    mysql: null
